# vim: ft=ansible
---

- name: Install Python
  apt: name={{ item }}
  with_items:
    - python2.7
    - python2.7-dev
    - python3
    - python3-dev
    - python-pip
    - python3-pip
    - python-virtualenv
    - virtualenvwrapper
    - ipython
